name: PR Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Build with JDK 17
        run: mvn -B install --no-transfer-progress -DskipTests

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Test with JDK 17
        run: mvn -v && mvn -B test

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Test with JDK 21
        run: mvn -v && mvn -B test

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 25
      - name: Test with JDK 25
        run: mvn -v && mvn -B test
